export type ResultStatus = "OK" | "ERROR";

export type ReturnType = "UNREDEEMED" | "RETURN";

export type PlacementType = "FBY" | "FBS" | "DBS" | "EXPRESS";

export type Turnover = "LOW" | "ALMOST_LOW" | "HIGH" | "VERY_HIGH" | "NO_SALES" | "FREE_STORE";

export type CampaignStockType = "FIT" | "FREEZE" | "AVAILABLE" | "QUARANTINE" | "UTILIZATION" | "DEFECT" | "EXPIRED";

export type Language = "RU" | "UZ";

export type OrderBuyerType = "PERSON" | "BUSINESS";

export type CurrencyType = "UZS" | "USD" | "RUB";

export type ShipmentRecipientType = "SHOP" | "DELIVERY_SERVICE" | "POST";

export type OrderDeliveryType = "DELIVERY" | "PICKUP" | "POST" | "DIGITAL" | "UNKNOWN";

export type OrderDeliveryPartnerType = "SHOP" | "YANDEX_MARKET" | "UNKNOWN";

export type OrderDeliveryDispatchType = "UNKNOWN" | "BUYER" | "MARKET_BRANDED_OUTLET" | "SHOP_OUTLET";

export type LogisticPointType = "WAREHOUSE" | "PICKUP_POINT" | "PICKUP_TERMINAL" | "PICKUP_POST_OFFICE" | "PICKUP_MIXED" | "PICKUP_RETAIL";

export type ReturnShipmentStatus =
| "CREATED"
  | "RECEIVED"
  | "IN_TRANSIT"
  | "READY_FOR_PICKUP"
  | "PICKED"
  | "LOST"
  | "EXPIRED"
  | "CANCELLED"
  | "FULFILMENT_RECEIVED"
  | "PREPARED_FOR_UTILIZATION"
  | "NOT_IN_DEMAND"
  | "UTILIZED"
  | "READY_FOR_EXPROPRIATION"
  | "RECEIVED_FOR_EXPROPRIATION"
  | "UNKNOWN";

export type ReturnStatus =
  | "STARTED_BY_USER"
  | "REFUND_IN_PROGRESS"
  | "REFUNDED"
  | "FAILED"
  | "WAITING_FOR_DECISION"
  | "DECISION_MADE"
  | "REFUNDED_WITH_BONUSES"
  | "REFUNDED_BY_SHOP"
  | "CANCELLED"
  | "REJECTED"
  | "COMPLETE_WITHOUT_REFUND"
  | "PREMODERATION_DISPUTE"
  | "PREMODERATION_DECISION_WAITING"
  | "PREMODERATION_DECISION_MADE"
  | "PREMODERATION_SELECT_DELIVERY"
  | "UNKNOWN";

export type ReturnDecisionType =
  | "FAST_REFUND_MONEY"
  | "REFUND_MONEY"
  | "REFUND_MONEY_INCLUDING_SHIPMENT"
  | "REPAIR"
  | "REPLACE"
  | "SEND_TO_EXAMINATION"
  | "DECLINE_REFUND"
  | "OTHER_DECISION"
  | "UNKNOWN";

export type ReturnDecisionReasonType =
  | "BAD_QUALITY"
  | "DOES_NOT_FIT"
  | "WRONG_ITEM"
  | "DAMAGE_DELIVERY"
  | "LOYALTY_FAIL"
  | "CONTENT_FAIL"
  | "DELIVERY_FAIL"
  | "UNKNOWN";


export type ReturnDecisionSubreasonType =
  | "USER_DID_NOT_LIKE"
  | "USER_CHANGED_MIND"
  | "DELIVERED_TOO_LONG"
  | "BAD_PACKAGE"
  | "DAMAGED"
  | "NOT_WORKING"
  | "INCOMPLETENESS"
  | "WRONG_ITEM"
  | "WRONG_COLOR"
  | "DID_NOT_MATCH_DESCRIPTION"
  | "WRONG_ORDER"
  | "WRONG_AMOUNT_DELIVERED"
  | "WRAPPING_DAMAGED"
  | "ITEM_WAS_USED"
  | "BROKEN"
  | "BAD_FLOWERS"
  | "PARCEL_MISSING"
  | "INCOMPLETE"
  | "UNKNOWN";

export type ReturnInstanceStatus =
  | "CREATED"
  | "RECEIVED"
  | "IN_TRANSIT"
  | "READY_FOR_PICKUP"
  | "PICKED"
  | "RECEIVED_ON_FULFILLMENT"
  | "CANCELLED"
  | "LOST"
  | "UTILIZED"
  | "PREPARED_FOR_UTILIZATION"
  | "EXPROPRIATED"
  | "NOT_IN_DEMAND";

export type ReturnInstanceStockType =
  | "FIT"
  | "DEFECT"
  | "ANOMALY"
  | "SURPLUS"
  | "EXPIRED"
  | "MISGRADING"
  | "UNDEFINED"
  | "INCORRECT_IMEI"
  | "INCORRECT_SERIAL_NUMBER"
  | "INCORRECT_CIS"
  | "PART_MISSING"
  | "NON_COMPLIENT"
  | "NOT_ACCEPTABLE"
  | "SERVICE"
  | "MARKDOWN"
  | "DEMO"
  | "REPAIR"
  | "FIRMWARE"
  | "UNKNOWN";

export type VatValue =
  | "NO_VAT"
  | "VAT_0"
  | "VAT_10"
  | "VAT_10_110"
  | "VAT_20"
  | "VAT_20_120"
  | "VAT_18"
  | "VAT_18_118"
  | "VAT_12"
  | "VAT_05"
  | "VAT_07"
  | "UNKNOWN_VALUE";

export type OrderStatus =
  | "PLACING"
  | "RETURNED"
  | "RESERVED"
  | "PARTIALLY_RETURNED"
  | "PENDING"
  | "CANCELLED"
  | "DELIVERED"
  | "PICKUP"
  | "UNPAID"
  | "PROCESSING"
  | "DELIVERY"
  | "UNKNOWN";

export type OrderSubstatus =
  | "RESERVATION_EXPIRED"
  | "USER_NOT_PAID"
  | "USER_UNREACHABLE"
  | "USER_CHANGED_MIND"
  | "USER_REFUSED_DELIVERY"
  | "USER_REFUSED_PRODUCT"
  | "SHOP_FAILED"
  | "USER_REFUSED_QUALITY"
  | "REPLACING_ORDER"
  | "PROCESSING_EXPIRED"
  | "PENDING_EXPIRED"
  | "SHOP_PENDING_CANCELLED"
  | "PENDING_CANCELLED"
  | "USER_FRAUD"
  | "RESERVATION_FAILED"
  | "USER_PLACED_OTHER_ORDER"
  | "USER_BOUGHT_CHEAPER"
  | "MISSING_ITEM"
  | "BROKEN_ITEM"
  | "WRONG_ITEM"
  | "PICKUP_EXPIRED"
  | "DELIVERY_PROBLEMS"
  | "LATE_CONTACT"
  | "CUSTOM"
  | "DELIVERY_SERVICE_FAILED"
  | "WAREHOUSE_FAILED_TO_SHIP"
  | "DELIVERY_SERVICE_UNDELIVERED"
  | "PREORDER"
  | "AWAIT_CONFIRMATION"
  | "STARTED"
  | "PACKAGING"
  | "READY_TO_SHIP"
  | "SHIPPED"
  | "ASYNC_PROCESSING"
  | "WAITING_USER_INPUT"
  | "WAITING_BANK_DECISION"
  | "BANK_REJECT_CREDIT_OFFER"
  | "CUSTOMER_REJECT_CREDIT_OFFER"
  | "CREDIT_OFFER_FAILED"
  | "AWAIT_DELIVERY_DATES_CONFIRMATION"
  | "SERVICE_FAULT"
  | "DELIVERY_SERVICE_RECEIVED"
  | "USER_RECEIVED"
  | "WAITING_FOR_STOCKS"
  | "AS_PART_OF_MULTI_ORDER"
  | "READY_FOR_LAST_MILE"
  | "LAST_MILE_STARTED"
  | "ANTIFRAUD"
  | "DELIVERY_USER_NOT_RECEIVED"
  | "DELIVERY_SERVICE_DELIVERED"
  | "DELIVERED_USER_NOT_RECEIVED"
  | "USER_WANTED_ANOTHER_PAYMENT_METHOD"
  | "USER_RECEIVED_TECHNICAL_ERROR"
  | "USER_FORGOT_TO_USE_BONUS"
  | "DELIVERY_SERVICE_NOT_RECEIVED"
  | "DELIVERY_SERVICE_LOST"
  | "SHIPPED_TO_WRONG_DELIVERY_SERVICE"
  | "DELIVERED_USER_RECEIVED"
  | "WAITING_TINKOFF_DECISION"
  | "COURIER_SEARCH"
  | "COURIER_FOUND"
  | "COURIER_IN_TRANSIT_TO_SENDER"
  | "COURIER_ARRIVED_TO_SENDER"
  | "COURIER_RECEIVED"
  | "COURIER_NOT_FOUND"
  | "COURIER_NOT_DELIVER_ORDER"
  | "COURIER_RETURNS_ORDER"
  | "COURIER_RETURNED_ORDER"
  | "WAITING_USER_DELIVERY_INPUT"
  | "PICKUP_SERVICE_RECEIVED"
  | "PICKUP_USER_RECEIVED"
  | "CANCELLED_COURIER_NOT_FOUND"
  | "COURIER_NOT_COME_FOR_ORDER"
  | "DELIVERY_NOT_MANAGED_REGION"
  | "INCOMPLETE_CONTACT_INFORMATION"
  | "INCOMPLETE_MULTI_ORDER"
  | "INAPPROPRIATE_WEIGHT_SIZE"
  | "TECHNICAL_ERROR"
  | "SORTING_CENTER_LOST"
  | "COURIER_SEARCH_NOT_STARTED"
  | "LOST"
  | "AWAIT_PAYMENT"
  | "AWAIT_LAVKA_RESERVATION"
  | "USER_WANTS_TO_CHANGE_ADDRESS"
  | "FULL_NOT_RANSOM"
  | "PRESCRIPTION_MISMATCH"
  | "DROPOFF_LOST"
  | "DROPOFF_CLOSED"
  | "DELIVERY_TO_STORE_STARTED"
  | "USER_WANTS_TO_CHANGE_DELIVERY_DATE"
  | "WRONG_ITEM_DELIVERED"
  | "DAMAGED_BOX"
  | "AWAIT_DELIVERY_DATES"
  | "LAST_MILE_COURIER_SEARCH"
  | "PICKUP_POINT_CLOSED"
  | "LEGAL_INFO_CHANGED"
  | "USER_HAS_NO_TIME_TO_PICKUP_ORDER"
  | "DELIVERY_CUSTOMS_ARRIVED"
  | "DELIVERY_CUSTOMS_CLEARED"
  | "FIRST_MILE_DELIVERY_SERVICE_RECEIVED"
  | "AWAIT_AUTO_DELIVERY_DATES"
  | "AWAIT_USER_PERSONAL_DATA"
  | "NO_PERSONAL_DATA_EXPIRED"
  | "CUSTOMS_PROBLEMS"
  | "AWAIT_CASHIER"
  | "WAITING_POSTPAID_BUDGET_RESERVATION"
  | "AWAIT_SERVICEABLE_CONFIRMATION"
  | "POSTPAID_BUDGET_RESERVATION_FAILED"
  | "AWAIT_CUSTOM_PRICE_CONFIRMATION"
  | "READY_FOR_PICKUP"
  | "TOO_MANY_DELIVERY_DATE_CHANGES"
  | "TOO_LONG_DELIVERY"
  | "DEFERRED_PAYMENT"
  | "POSTPAID_FAILED"
  | "INCORRECT_PERSONAL_DATA"
  | "UNKNOWN";
